theme: jekyll-theme-cayman
title: The 6th International Workshop on User Understanding from Big Data Workshop (U2BigData 2025)
description: In conjunction with IEEE Big Data Conference, Macau SAR, China, December 8-11, 2025
