theme: jekyll-theme-cayman
title: The 4nd International Workshop on User Understanding from Big Data Workshop (U2BigData 2023)
description: In conjunction with IEEE Big Data Conference, Sorrento, Italy, December 15-18, 2023
