theme: jekyll-theme-cayman
title: The 2nd International Workshop on User Understanding from Big Data Workshop (U2BigData 2020)
description: In conjunction with IEEE Big Data Conference, Orlando, December 12-16, 2021
