theme: jekyll-theme-cayman
title: The 5th International Workshop on User Understanding from Big Data Workshop (U2BigData 2024)
description: In conjunction with IEEE Big Data Conference, Washington DC, USA, December 15-18, 2024
