theme: jekyll-theme-cayman
title: The 3nd International Workshop on User Understanding from Big Data Workshop (U2BigData 2022)
description: In conjunction with IEEE Big Data Conference, Osaka, December 17, 2022 8:30am - 12:30pm
