theme: jekyll-theme-cayman
title: The 2nd International Workshop on User Understanding from Big Data Workshop (U2BigData 2021)
description: In conjunction with IEEE Big Data Conference, Orlando, December 15-18, 2021
